### ISSUE TITLE
raise ParserError

### ISSUE THREAD

**Issue by BlackD14** [mansuf/zippyshare-downloader#10]
![gambar](https://user-images.githubusercontent.com/44439014/146694548-5a2e83df-562a-414d-ae73-25110184589c.png)

**Comment by mansuf** [comment]
Gonna look for this, thanks for the info.

**Comment by mansuf** [comment]
Fixed in release [`v0.2.0`](https://github.com/mansuf/zippyshare-downloader/releases/tag/v0.2.0), update your zippyshare-downloader
