### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by BlekkkDIII** [mansuf/zippyshare-downloader#12]
i want to show download url, how to do it?

**Comment by mansuf** [comment]
The output already showed the download url, did you mean "show download url only" ?

**Comment by BlekkkDIII** [comment]
> ```
> $ zippyshare-dl "https://www61.zippyshare.com/v/op8XYTSL/file.html" --no-download
> [INFO] Grabbing required informations in https://www61.zippyshare.com/v/op8XYTSL/file.html
> 
> Result from url https://www61.zippyshare.com/v/op8XYTSL/file.html
> ==================================================================
> Name          : Weakest Link Christmas Special.mp4.part1.rar
> Size          : 500 MB
> Date uploaded : 23-12-2021 04:15
> Download URL  : https://www61.zippyshare.com/d/op8XYTSL/25376/Weakest%20Link%20Christmas%20Special.mp4.part1.rar
> ```
> 
> The output already showed the download url, did you mean "show download url only" ?

Yes
