### ISSUE TITLE
i always get the error is not a zippyshare ure

### ISSUE THREAD

**Issue by Manni1000** [mansuf/zippyshare-downloader#13]
it always says invalid url

**Comment by mansuf** [comment]
What url did you use ?

Show it to me0

**Comment by wonderlus5** [comment]
I speculate the lack of response signifies the user resolved the issue.

In my experience, always "the bad" that receives the most action, be it even by own mistake: When everything is alright or resolved, sometimes people tend to, let say, not write on Github's issues. Will over half a year be efficient to close the issue for the lack of thereof, maybe need a year, two, three or is better to close after so many months passed? Of course leave the comment section open for the user if they are just in a long break.

To me it works on Android's Termux environment surpsingly well. Loads links that look like https://www000.zippyshare.com/v/somefile/file.html, all OK.

**Comment by mansuf** [comment]
> When everything is alright or resolved, sometimes people tend to, let say, not write on Github's issues.

Yeah sometimes people do that actually. Alright this issue is closed since there is no response for 3 months.
