### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by ReaPeRz38** [mansuf/zippyshare-downloader#16]
Hello, as soon as I try to import the module I get an error (I'm running on python 3.10): 

````
C:\Users\matth\OneDrive\Bureau>python test.py
Traceback (most recent call last):
  File "C:\Users\matth\OneDrive\Bureau\test.py", line 3, in <module>
    from zippyshare_downloader import *
ModuleNotFoundError: No module named 'zippyshare_downloader'
```

**Comment by mansuf** [comment]
Did you install it correctly ? seems like it cannot find `zippyshare-downloader` library

**Comment by ReaPeRz38** [comment]
![image](https://user-images.githubusercontent.com/59476172/185355476-39e2a09d-8093-43f1-83c7-ea2b7af4f095.png)

**Comment by mansuf** [comment]
Hmmmmm, it looks like your `pip` are using different python. Can you show me output of these commands ? 

```shell
pip --version
python --version
```

**Comment by mansuf** [comment]
Or you can try install the library from `python -m pip` command and try to import it

```shell
python -m pip install zippyshare-downloader
```

**Comment by ReaPeRz38** [comment]
![image](https://user-images.githubusercontent.com/59476172/185358447-8aae0d33-15fb-482f-9bde-a80c0a3129cc.png)
![image](https://user-images.githubusercontent.com/59476172/185358574-389a021e-4227-4dcc-ae66-ee60d4fdc186.png)

**Comment by mansuf** [comment]
See, pip are using python `3.10` and your `python` command are using version `3.9.10`. So it cannot import zippyshare-downloader from python `3.9.10` and zippyshare-downloader are installed in python `3.10` in your system. 

So if you wanna run the python that has pip libraries installed use python 3.10 or if you have `py` launcher installed you can run `py -3.10 test.py` 

And the error `No module named pip`, it looks like you are installing python without pip.

**Comment by ReaPeRz38** [comment]
thx my bad i didn't see that i have 2 version of python installed
