### ISSUE TITLE
Inheritance class aiohttpProxiedSession from ClientSession is forbidden

### ISSUE THREAD

**Issue by leolapi4** [mansuf/zippyshare-downloader#23]
Hi!
It raises error.

Python version:

> d:\JDownloader\zippyshare-downloader-0.3.4>python
> **Python 3.8.2** (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)] on win32

CLI output:

> d:\JDownloader\zippyshare-downloader-0.3.4>python -m zippyshare_downloader https://filecrypt.cc/Container/8B69C3762B.html
> Traceback (most recent call last):
>   File "C:\Users\Leolapi4\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 184, in _run_module_as_main
>     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
>   File "C:\Users\Leolapi4\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 143, in _get_module_details
>     return _get_module_details(pkg_main_name, error)
>   File "C:\Users\Leolapi4\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 110, in _get_module_details
>     __import__(pkg_name)
>   File "d:\JDownloader\zippyshare-downloader-0.3.4\zippyshare_downloader\__init__.py", line 11, in <module>
>     from .network import *
>   File "d:\JDownloader\zippyshare-downloader-0.3.4\zippyshare_downloader\network.py", line 23, in <module>
>     class aiohttpProxiedSession(aiohttp.ClientSession):
>   File "C:\Users\Leolapi4\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiohttp-4.0.0a1-py3.8-win32.egg\aiohttp\client.py", line 265, in __init_subclass__
>     raise TypeError("Inheritance class {} from ClientSession "
> **TypeError: Inheritance class aiohttpProxiedSession from ClientSession is forbidden**

**Comment by mansuf** [comment]
Don't use aiohttp version 4.x

Use version 3.x instead

```
pip uninstall aiohttp
pip install aiohttp<4
```

**Comment by leolapi4** [comment]
The second command immediately returns file not found error.

**Comment by mansuf** [comment]
Oh my bad, use double quotation mark for `aiohttp<4`


```
pip install "aiohttp<4"
```

**Comment by leolapi4** [comment]
It is solved. Now I've got another error - not zippyshare link provided. But I saw this issue in solved. Thanks for the assistance!
