### ISSUE TITLE
Add support to use and bind IP to specific Network address

### ISSUE THREAD

**Issue by whulkhulk** [mansuf/zippyshare-downloader#25]
Is it possible to use and Bind IP to specific Network address e.g:
zippyshare-downloader /bindip 192.191.248.70
zippyshare-downloader /bindip "Realtek PCIe Family Control"
Thanks

**Comment by mansuf** [comment]
Sorry, the app does not have that feature and i'm not interested adding that feature.

You can access requests session from `zippyshare_downloader.network` if you want to do hacky thing on your own.

```python
from zippyshare_downloader.network import Net

# requests session
rs = Net.requests

# aiohttp session
as = Net.aiohttp
```

**Comment by whulkhulk** [comment]
> Sorry, the app does not have that feature and i'm not interested adding that feature.
> 
> You can access requests session from `zippyshare_downloader.network` if you want to do hacky thing on your own.
> 
> ```python
> from zippyshare_downloader.network import Net
> 
> # requests session
> rs = Net.requests
> 
> # aiohttp session
> as = Net.aiohttp
> ```

Thanks for reply.
Ok, Can you please elaborate more since I don't know thing about python?
