### ISSUE TITLE
Filenames are still not writing correctly.

### ISSUE THREAD

**Issue by Ahmneo** [mansuf/zippyshare-downloader#5]
I executed the following in a Google Colab session:

!zippyshare-downloader https://www103.zippyshare.com/v/7S3vO6Op/file.html --verbose --progress-bar && zippyshare-downloader https://www103.zippyshare.com/v/4jjHYw2d/file.html --verbose --progress-bar && zippyshare-downloader https://www103.zippyshare.com/v/5cjVlAUm/file.html --verbose --progress-bar && zippyshare-downloader https://www103.zippyshare.com/v/ZZotSH97/file.html --verbose --progress-bar && zippyshare-downloader https://www103.zippyshare.com/v/ebuvfMVY/file.html --verbose --progress-bar && zippyshare-downloader https://www103.zippyshare.com/v/EjkGpC8i/file.html --verbose --progress-bar && zippyshare-downloader https://www103.zippyshare.com/v/gIjQiQfx/file.html --verbose --progress-bar && zippyshare-downloader https://www103.zippyshare.com/v/fJNQgAi3/file.html --verbose --progress-bar

And got the following output:

[INFO] Fetching URL "https://www103.zippyshare.com/v/7S3vO6Op/file.html"
[INFO] Parsing info
[INFO] Getting Download URL from "https://www103.zippyshare.com/v/7S3vO6Op/file.html"
[INFO] Downloading "Fear.the.Walking.Dead.S06E08.The.Door.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv.par..."
Downloading data from https://www103.zippyshare.com/d/7S3vO6Op/859190/Fear.the.Walking.Dead.S06E08.The.Door.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv.part1.rar (500.0 MB)

file_sizes: 100%|████████████████████████████| 524M/524M [00:46<00:00, 11.4MB/s]
Successfully downloaded file to Fear.the.Walking.Dead.S06E08.The.Door.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv.par...
{'name_file': 'Fear.the.Walking.Dead.S06E08.The.Door.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv.par...', 'size': '500 MB', 'date_upload': '04-04-2021 17:36', 'download_url': 'https://www103.zippyshare.com/d/7S3vO6Op/859190/Fear.the.Walking.Dead.S06E08.The.Door.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv.part1.rar'}
[INFO] Fetching URL "https://www103.zippyshare.com/v/4jjHYw2d/file.html"
[INFO] Parsing info
[INFO] Getting Download URL from "https://www103.zippyshare.com/v/4jjHYw2d/file.html"
[INFO] Downloading "Fear.the.Walking.Dead.S06E08.The.Door.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv.par..."
Replace is False and data exists, so doing nothing. Use replace=True to re-download the data.
{'name_file': 'Fear.the.Walking.Dead.S06E08.The.Door.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv.par...', 'size': '500 MB', 'date_upload': '04-04-2021 17:37', 'download_url': 'https://www103.zippyshare.com/d/4jjHYw2d/430404/Fear.the.Walking.Dead.S06E08.The.Door.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv.part2.rar'}
[INFO] Fetching URL "https://www103.zippyshare.com/v/5cjVlAUm/file.html"
[INFO] Parsing info
[INFO] Getting Download URL from "https://www103.zippyshare.com/v/5cjVlAUm/file.html"
[INFO] Downloading "Fear.the.Walking.Dead.S06E08.The.Door.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv.par..."
Replace is False and data exists, so doing nothing. Use replace=True to re-download the data.
{'name_file': 'Fear.the.Walking.Dead.S06E08.The.Door.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv.par...', 'size': '500 MB', 'date_upload': '04-04-2021 17:38', 'download_url': 'https://www103.zippyshare.com/d/5cjVlAUm/762364/Fear.the.Walking.Dead.S06E08.The.Door.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv.part3.rar'}
[INFO] Fetching URL "https://www103.zippyshare.com/v/ZZotSH97/file.html"
[INFO] Parsing info
[INFO] Getting Download URL from "https://www103.zippyshare.com/v/ZZotSH97/file.html"
[INFO] Downloading "Fear.the.Walking.Dead.S06E08.The.Door.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv.par..."
Replace is False and data exists, so doing nothing. Use replace=True to re-download the data.
{'name_file': 'Fear.the.Walking.Dead.S06E08.The.Door.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv.par...', 'size': '500 MB', 'date_upload': '04-04-2021 17:38', 'download_url': 'https://www103.zippyshare.com/d/ZZotSH97/150614/Fear.the.Walking.Dead.S06E08.The.Door.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv.part4.rar'}
[INFO] Fetching URL "https://www103.zippyshare.com/v/ebuvfMVY/file.html"
[INFO] Parsing info
[INFO] Getting Download URL from "https://www103.zippyshare.com/v/ebuvfMVY/file.html"
[INFO] Downloading "Fear.the.Walking.Dead.S06E08.The.Door.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv.par..."
Replace is False and data exists, so doing nothing. Use replace=True to re-download the data.
{'name_file': 'Fear.the.Walking.Dead.S06E08.The.Door.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv.par...', 'size': '500 MB', 'date_upload': '04-04-2021 17:39', 'download_url': 'https://www103.zippyshare.com/d/ebuvfMVY/860808/Fear.the.Walking.Dead.S06E08.The.Door.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv.part5.rar'}
[INFO] Fetching URL "https://www103.zippyshare.com/v/EjkGpC8i/file.html"
[INFO] Parsing info
[INFO] Getting Download URL from "https://www103.zippyshare.com/v/EjkGpC8i/file.html"
[INFO] Downloading "Fear.the.Walking.Dead.S06E08.The.Door.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv.par..."
Replace is False and data exists, so doing nothing. Use replace=True to re-download the data.
{'name_file': 'Fear.the.Walking.Dead.S06E08.The.Door.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv.par...', 'size': '500 MB', 'date_upload': '04-04-2021 17:40', 'download_url': 'https://www103.zippyshare.com/d/EjkGpC8i/340215/Fear.the.Walking.Dead.S06E08.The.Door.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv.part6.rar'}
[INFO] Fetching URL "https://www103.zippyshare.com/v/gIjQiQfx/file.html"
[INFO] Parsing info
[INFO] Getting Download URL from "https://www103.zippyshare.com/v/gIjQiQfx/file.html"
[INFO] Downloading "Fear.the.Walking.Dead.S06E08.The.Door.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv.par..."
Replace is False and data exists, so doing nothing. Use replace=True to re-download the data.
{'name_file': 'Fear.the.Walking.Dead.S06E08.The.Door.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv.par...', 'size': '500 MB', 'date_upload': '04-04-2021 17:40', 'download_url': 'https://www103.zippyshare.com/d/gIjQiQfx/908321/Fear.the.Walking.Dead.S06E08.The.Door.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv.part7.rar'}
[INFO] Fetching URL "https://www103.zippyshare.com/v/fJNQgAi3/file.html"
[INFO] Parsing info
[INFO] Getting Download URL from "https://www103.zippyshare.com/v/fJNQgAi3/file.html"
[INFO] Downloading "Fear.the.Walking.Dead.S06E08.The.Door.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv.par..."
Replace is False and data exists, so doing nothing. Use replace=True to re-download the data.
{'name_file': 'Fear.the.Walking.Dead.S06E08.The.Door.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv.par...', 'size': '256.31 MB', 'date_upload': '04-04-2021 17:40', 'download_url': 'https://www103.zippyshare.com/d/fJNQgAi3/263794/Fear.the.Walking.Dead.S06E08.The.Door.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv.part8.rar'}

**Comment by mansuf** [comment]
![image](https://user-images.githubusercontent.com/43638783/113522713-1e0dfe80-95cd-11eb-8e36-dd013847a204.png)
I think zippyshare didn't provide full filename if the filename is too long.

On my way to fix this.

**Comment by mansuf** [comment]
![image](https://user-images.githubusercontent.com/43638783/113522969-0d5e8800-95cf-11eb-9de5-5e91cedb1a85.png)

this issue fixed on https://github.com/mansuf/zippyshare-downloader/commit/dedd1dc7ce78029a7ea666b67b3ef914829db65d, the update will release soon (v0.0.17)

**Comment by mansuf** [comment]
the update is released (v0.0.17) and this issue should be fixed.

Thank you for your contribution !
