### ISSUE TITLE
[Feature Request] Custom Filename

### ISSUE THREAD

**Issue by X-Gorn** [mansuf/zippyshare-downloader#6]
Add feature to change the filename after downloaded

**Comment by mansuf** [comment]
I will think about it, thank you for your suggestion

**Comment by mansuf** [comment]
Hi !, here some good news for you :D. 

This feature is freshly added in [`v0.0.18`](https://github.com/mansuf/zippyshare-downloader/releases/tag/v0.0.18).

You can start update your `zippyshare-downloader`, and enjoy this cool features 😄

**Comment by mansuf** [comment]
if you have another issue that related to this features, you can reopen this issue 👍
