### ISSUE TITLE
Python script alternate download method is not working.

### ISSUE THREAD

**Issue by Ahmneo** [mansuf/zippyshare-downloader#8]
I ran the following python script in Google Colab:

from zippyshare_downloader import Zippyshare

z = Zippyshare()

info1 = z.extract_info('https://www26.zippyshare.com/v/pz2tYmok/file.html', download=False)

from download import download

# you can pass verbose, progress_bar, and replace arguments as well
download(info1['download_url'], 'Weeds.S05E01.Wonderful.Wonderful.1080p.DTS-HD.MA.7.1.AVC.REMUX-FraMeSToR.part01.rar')

# and that's it.

And got the following output:

[INFO] Fetching URL "https://www26.zippyshare.com/v/pz2tYmok/file.html"
[INFO] Parsing info
[INFO] Getting Download URL from "https://www26.zippyshare.com/v/pz2tYmok/file.html"
Traceback (most recent call last):
  File "/content/drive/MyDrive/Unrar/Weeds/Season 05/weedss05.py", line 5, in <module>
    info1 = z.extract_info('https://www26.zippyshare.com/v/pz2tYmok/file.html', download=False)
  File "/usr/local/lib/python3.7/dist-packages/zippyshare_downloader/__init__.py", line 237, in extract_info
    custom_filename=custom_filename
  File "/usr/local/lib/python3.7/dist-packages/zippyshare_downloader/__init__.py", line 177, in _extract_info
    info = self._get_info(url, r)
  File "/usr/local/lib/python3.7/dist-packages/zippyshare_downloader/__init__.py", line 161, in _get_info
    'download_url': self._get_url(u, r)
  File "/usr/local/lib/python3.7/dist-packages/zippyshare_downloader/__init__.py", line 74, in _get_url
    raise ParserError('omg attribute in download button javascript cannot be found')
zippyshare_downloader.errors.ParserError: omg attribute in download button javascript cannot be found

**Comment by X-Gorn** [comment]
same here

**Comment by mansuf** [comment]
Google colab using python jupyter notebook (.ipynb).

when i trying use `zippyshare-downloader` on default python (.py), it just works fine.<br>But, when i trying use `zippyshare-downloader` on python jupyter notebook in google colab or local python jupyter, it broke.

## it seems like `zippyshare-downloader` doesn't support running on python jupyter notebook.

I'm investigating more deeper about this.

Thank you kindly :D.

**Comment by mansuf** [comment]
it seems like zippyshare changing their code to the previous code.

Fortunately, `zippyshare-downloader` version 0.0.13 lower has previous pattern parser for zippyshare, you can start install `zippyshare-downloader` version 0.0.13 lower (`pip install zippyshare-downloader==0.0.13`)<br>**BUT, some features in latest version (v0.0.18) is not exist on v0.0.13, so yeah be patient while i'm trying to fix this :D**.

I'm adding multiple patterns parser to the next release, so zippyshare-downloader can still usable while zippyshare code is changing

**Comment by mansuf** [comment]
This issue is fixed on release [`v0.0.19`](https://github.com/mansuf/zippyshare-downloader/releases/tag/v0.0.19)
